# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confronto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guerreiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.IntegerField(default=0)),
                ('v2', models.IntegerField(default=0)),
                ('confronto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confronto.Confronto')),
                ('gz1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gz1', to='dbz.Guerreiro')),
                ('gz2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gz2', to='dbz.Guerreiro')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Titulo')),
            ],
        ),
    ]
