# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbz', '0002_auto_20180506_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='foto',
            field=models.CharField(default='empty', max_length=200, verbose_name='foto'),
            preserve_default=False,
        ),
    ]
