# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbz', '0003_titulo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='guerreiro',
            name='season',
            field=models.IntegerField(default=1),
        ),
    ]
