# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbz', '0004_guerreiro_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.IntegerField(default=1, verbose_name='season')),
            ],
        ),
        migrations.AlterField(
            model_name='guerreiro',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='dbz.Season'),
        ),
    ]
