# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confronto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(max_length=200)),
                ('time2', models.CharField(max_length=200)),
                ('data_jogo', models.DateTimeField(verbose_name='Data Confronto')),
                ('data_reserv', models.DateTimeField(auto_now=True, verbose_name='Data Reserva')),
                ('valendo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='confronto',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confronto.Jogo'),
        ),
    ]
